### ISSUE TITLE
How to find app.asar file in linux ?

### ISSUE THREAD

**Issue by BDadmehr0** [e9x/electron-injector#1]
In Linux, the **Krunker Official Client** version of the game has only one file called **setup.AppImage**
which is executed only by running this one game file

**Comment by e9x** [comment]
You can extract the AppImage to a folder then enter the resources directory and grab the asar.
https://docs.appimage.org/user-guide/run-appimages.html#extract-the-contents-of-an-appimage

In a terminal in your home directory:

1. Grab Krunker's AppImage and save to downloads:
   (Assuming you haven't saved setup.AppImage to Downloads already)
   ```sh
   wget https://client2.krunker.io/setup.AppImage -P ./Downloads
   chmod +x ./Downloads/setup.AppImage
   ```
4. Make a new directory for the AppImage files and enter it:
   ```sh
   mkdir krunker
   cd krunker
   ```
4. Extract by passing `--appimage-extract` to the AppImage:
   ```sh
   ../Downloads/setup.AppImage --appimage-extract
   ```

The AppImage files should be available in a directory at `~/krunker/squashfs-root`.

The app.asar is located at `~/krunker/squashfs-root/resources/app.asar`. You can patch it like you would on Windows.

I'm not familiar with how you can repack an AppImage after extraction, but you should be able to just run the game from your command line:

In a terminal in your home directory:
```sh
./krunker/squashfs-root/AppRun
```

Let me know how it goes.

*TODO: add these instructions somewhere in the repository*
